org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=26.2
mc_version_tag=26.2.x
loader_version=0.19.3
fabric_version=0.154.2+26.2

mod_version=1.2.0
maven_group=io.serge.flashbackextras
archives_base_name=flashback-extras
flashback_version=0.41.1
github_repo=sgerodes/flashback-extras
