org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=26.3
mc_version_tag=26.3.x
loader_version=0.19.5
fabric_version=0.160.5+26.3

mod_version=1.3.0
maven_group=io.serge.flashbackextras
archives_base_name=flashback-extras
flashback_version=0.43.4
github_repo=sgerodes/flashback-extras
